name: .NET Tests (Unit + Integration)

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on PRs to main branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project in Debug mode
      - name: Build project (Debug)
        run: dotnet build --no-restore

      # Run all tests (Unit + Integration) with detailed output
      - name: Run All Tests
        run: |
            dotnet test "PriceComparisonWebsite.Tests/PriceComparisonWebsite.Tests.csproj" --no-build --verbosity normal --logger "console;verbosity=detailed" --logger "trx;LogFileName=test-results.trx"

      #  Upload test results as an artifact
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: ./PriceComparisonWebsite.Tests/TestResults/test-results.trx

      # Display test summary in GitHub Actions
      - name: Generate Test Summary
        uses: zyborg/dotnet-tests-report@v1
        with:
          output: summary.md
